"""atualiza_modelo_com_diretor_e_genero

Revision ID: 9fc02719ae33
Revises: 0001_initial_movie_schema
Create Date: 2026-09-27 21:47:46.715328

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9fc02719ae33'
down_revision: Union[str, Sequence[str], None] = '0001_initial_movie_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diretor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_movies', schema=None) as batch_op:
        batch_op.drop_column('genero')
        batch_op.drop_column('diretor')

    # ### end Alembic commands ###
